import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";


const oswald = Oswald({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} h-full antialiased`}
    >
      <head>
        <title>The Hotel Company</title>
        <meta name="description" content="Luxury Hotel in Algiers" />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
